"""Dodanie kolumny restaurant_cost do tabeli City

Revision ID: 2463705847b3
Revises: 475b55c755b4
Create Date: 2025-03-20 12:37:28.544706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2463705847b3'
down_revision = '475b55c755b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_cost', sa.Integer(), nullable=True))
        batch_op.drop_column('price_in_restaurant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_in_restaurant', sa.INTEGER(), nullable=True))
        batch_op.drop_column('restaurant_cost')

    # ### end Alembic commands ###
