"""Dodanie kolumny restaurant_cost do tabeli City

Revision ID: 475b55c755b4
Revises: 
Create Date: 2025-03-20 12:36:18.806638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475b55c755b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_in_restaurant', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('price_in_restaurant')

    # ### end Alembic commands ###
