"""Dodana nowa kolumna apartament_rental

Revision ID: 5fa1f8146112
Revises: 2463705847b3
Create Date: 2025-03-20 21:32:14.627903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa1f8146112'
down_revision = '2463705847b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartament_rental', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('apartament_rental')

    # ### end Alembic commands ###
